spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root

  jackson:
    default-property-inclusion: NON_NULL

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: book_service
    user: root
    password: root
#  cloud:
#    config:
#      enabled: true
server:
  port: ${PORT}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      default:
        limit-for_period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      foo-bar:
        wait-duration: 3s
        max-attempts: 7
        enable-exponential-backoff: false #aumenta o tempo exponencialmente
      default:
        max-attempts: 5

springdoc:
  show-actuator: true
  api-docs:
    path: book-service/v3/api-docs